# Generated by Django 4.2.10 on 2024-02-14 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 15, 18, 23, 273447, tzinfo=datetime.timezone.utc), verbose_name='Fecha Publicación'),
        ),
    ]
